apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project-staging
images:
  - name: CREATE_POST_RUN
    newName: kirillstrelkov/create-post-run
    newTag: a1f2e4f64863b314e95d27668e7d204b08ff70d7
  - name: PG_BACKUP_IMAGE
    newName: kirillstrelkov/pg-backup
    newTag: a1f2e4f64863b314e95d27668e7d204b08ff70d7
  - name: TODO_APP_APP
    newName: kirillstrelkov/todo-app-app
    newTag: a1f2e4f64863b314e95d27668e7d204b08ff70d7
  - name: TODO_BACKEND_APP
    newName: kirillstrelkov/todo-backend-app
    newTag: a1f2e4f64863b314e95d27668e7d204b08ff70d7
  - name: TODO_BROADCASTER_APP
    newName: kirillstrelkov/todo-broadcaster-app
    newTag: 357ff3bb18d703801673809850de813e299ebbfe
namePrefix: staging-
resources:
  - ./secrets.yaml
  - ./../../base
  - ./ingress.yaml
  - ./persistent-volume-claim.yaml
  - ./persistent-volume.yaml
patches:
  - path: patch-config-map.yaml
    target:
      kind: ConfigMap
      name: todo-app-cm
