apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project-prod
images:
- name: CREATE_POST_RUN
  newName: kirillstrelkov/create-post-run
  newTag: a1f2e4f64863b314e95d27668e7d204b08ff70d7
- name: PG_BACKUP_IMAGE
  newName: kirillstrelkov/pg-backup
  newTag: a1f2e4f64863b314e95d27668e7d204b08ff70d7
- name: TODO_APP_APP
  newName: kirillstrelkov/todo-app-app
  newTag: 50dbed1f8fda4eb147c25c40640a7348246bfc69
- name: TODO_BACKEND_APP
  newName: kirillstrelkov/todo-backend-app
  newTag: 50dbed1f8fda4eb147c25c40640a7348246bfc69
- name: TODO_BROADCASTER_APP
  newName: kirillstrelkov/todo-broadcaster-app
  newTag: 357ff3bb18d703801673809850de813e299ebbfe
namePrefix: production-
resources:
- ./secrets.yaml
- ./../../base
- ./gateway.yaml
- ./health-check.yaml
- ./backup-cronjob.yaml
- ./persistent-volume-claim.yaml
configurations:
- kustomize-config.yaml
patches:
- path: patch-broadcaster-dep.yaml
  target:
    kind: Deployment
    name: todo-broadcaster-dep
- path: patch-config-map.yaml
  target:
    kind: ConfigMap
    name: todo-app-cm
