nameReference:
  - kind: Service
    fieldSpecs:
      - kind: HTTPRoute
        path: spec/rules/backendRefs/name
      - kind: HealthCheckPolicy
        path: spec/targetRef/name
  - kind: Gateway
    fieldSpecs:
      - kind: HTTPRoute
        path: spec/parentRefs/name
