apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./configmap.yaml
  - ./cronjob.yaml
  - ./deployment.yaml
  - ./broadcaster-dep.yaml
  - ./service.yaml
  - ./service_backend.yaml
  - ./statefulset.yaml
