apiVersion: v1
kind: Service
metadata:
  name: todo-app-svc
spec:
  type: ClusterIP
  selector:
    app: todo-app-app
  ports:
    - name: http
      protocol: TCP
      port: 1234
      targetPort: 8080
